"""made vote player id and ct app id non nullable

Revision ID: d8e9b4e2df88
Revises: a381a5c124c1
Create Date: 2025-06-01 00:56:17.532322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8e9b4e2df88'
down_revision: Union[str, None] = 'a381a5c124c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vote', 'ct_app_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'ct_app_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vote', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
