"""lastest update 23-4-025-2

Revision ID: b28c86c2bf0d
Revises: b497e3ed570b
Create Date: 2025-04-23 21:05:39.603010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b28c86c2bf0d'
down_revision: Union[str, None] = 'b497e3ed570b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
