"""added refresh token key field to users

Revision ID: a381a5c124c1
Revises: 724cfab9d99b
Create Date: 2025-05-12 02:20:30.482663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a381a5c124c1'
down_revision: Union[str, None] = '724cfab9d99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token_key', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token_key')
    # ### end Alembic commands ###
