"""made vote player id and ct app id non-nullable again

Revision ID: 085d6d041e3b
Revises: 774a1e026194
Create Date: 2025-06-01 06:35:55.949355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '085d6d041e3b'
down_revision: Union[str, None] = '774a1e026194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vote', 'ct_app_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'ct_app_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vote', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
