"""added picture and alive fields to player table

Revision ID: e78521d7fcad
Revises: 21c590b313a6
Create Date: 2025-06-08 05:38:05.001523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e78521d7fcad'
down_revision: Union[str, None] = '21c590b313a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('player', sa.Column('alive', sa.Boolean(), nullable=False, server_default=str(True)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'alive')
    op.drop_column('player', 'picture')
    # ### end Alembic commands ###
