"""added rct

Revision ID: 21c590b313a6
Revises: 085d6d041e3b
Create Date: 2025-06-07 06:26:58.873730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21c590b313a6'
down_revision: Union[str, None] = '085d6d041e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barrierrecord', sa.Column('reverse_cursed_technique_counter', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barrierrecord', 'reverse_cursed_technique_counter')
    # ### end Alembic commands ###
