"""lastest update 2

Revision ID: 9f0d0d7ab3d6
Revises: 72eeffd42a71
Create Date: 2025-04-16 13:03:17.474645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f0d0d7ab3d6'
down_revision: Union[str, None] = '72eeffd42a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
