"""making usernamedb auto creation in DB - made usernamedb nullable

Revision ID: b6e184f6346b
Revises: 12f40ef2bc4f
Create Date: 2025-07-02 21:42:47.254065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6e184f6346b'
down_revision: Union[str, None] = '12f40ef2bc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'usernamedb',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'usernamedb',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
