"""lastest update 23-4-025 3

Revision ID: 481621a7cbf9
Revises: b28c86c2bf0d
Create Date: 2025-04-23 21:17:10.866704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '481621a7cbf9'
down_revision: Union[str, None] = 'b28c86c2bf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
