"""made player, cursed tecnique, and application compulsory/non nullable to each other respective relationship

Revision ID: 6fc0527c016e
Revises: 26a15bd3cfe4
Create Date: 2025-07-06 13:31:57.566527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fc0527c016e'
down_revision: Union[str, None] = '26a15bd3cfe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ctapp', 'ct_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cursedtechnique', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cursedtechnique', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ctapp', 'ct_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
