"""changed player and ctapp to delete vote if either is deleted

Revision ID: 78aa0b379dc9
Revises: 5c97aafa1971
Create Date: 2025-07-09 07:07:51.037567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78aa0b379dc9'
down_revision: Union[str, None] = '5c97aafa1971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vote_player_id_fkey', 'vote', type_='foreignkey')
    op.drop_constraint('vote_ct_app_id_fkey', 'vote', type_='foreignkey')
    op.create_foreign_key(None, 'vote', 'player', ['player_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vote', 'ctapp', ['ct_app_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.create_foreign_key('vote_ct_app_id_fkey', 'vote', 'ctapp', ['ct_app_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('vote_player_id_fkey', 'vote', 'player', ['player_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
