"""removed usernamedb from the database, and made it a hybrid property of user

Revision ID: c707681be11c
Revises: b6e184f6346b
Create Date: 2025-07-02 22:28:09.804029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c707681be11c'
down_revision: Union[str, None] = 'b6e184f6346b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_usernamedb', table_name='user')
    op.drop_column('user', 'usernamedb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernamedb', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_usernamedb', 'user', ['usernamedb'], unique=True)
    # ### end Alembic commands ###
