"""match non nullable in vote table

Revision ID: 5c97aafa1971
Revises: 0225a8cd790e
Create Date: 2025-07-09 07:04:38.583658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c97aafa1971'
down_revision: Union[str, None] = '0225a8cd790e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=False, server_default=str(10))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
