"""added possible draw bool value for match winner, to allow for draw

Revision ID: 12f40ef2bc4f
Revises: e78521d7fcad
Create Date: 2025-06-23 22:59:01.101955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12f40ef2bc4f'
down_revision: Union[str, None] = 'e78521d7fcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('draw', sa.Boolean(), nullable=False, server_default=str(False)))
    op.create_index(op.f('ix_match_draw'), 'match', ['draw'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_draw'), table_name='match')
    op.drop_column('match', 'draw')
    # ### end Alembic commands ###
