// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * BarrierRecordInfo
 */
export const zBarrierRecordInfo = z.object({
    domain_counter: z.optional(z.int()).default(0),
    simple_domain_counter: z.optional(z.int()).default(0),
    binding_vow_counter: z.optional(z.int()).default(0),
    reverse_cursed_technique_counter: z.optional(z.int()).default(0),
    id: z.int(),
    barrier_tech_id: z.int(),
    match_id: z.int()
});

/**
 * BarrierTechInfo
 *
 * Represents barrier technique information for client-side.
 *
 * Attributes:
 * id (int): Unique identifier for the barrier technique.
 * player_id: int
 * domain_expansion: bool = Field(default=False, description="the player's domain expansion")
 * binding_vow: bool = Field(default=False, description="the player's binding vow")
 * simple_domain: bool = Field(default=False, description="the player's simple domain")
 * The times are useful for know when to activate/deactivate the techniques
 * de_end_time: datetime | None = Field(default=None, description="the time a player cast their domain")
 * bv_end_time: datetime | None = Field(default=None, description="the time a player cast their binding_vow")
 * sd_end_time: datetime | None = Field(default=None, description="the time a player cast their simple_domain")
 */
export const zBarrierTechInfo = z.object({
    domain_expansion: z.optional(z.boolean()).default(false),
    binding_vow: z.optional(z.boolean()).default(false),
    simple_domain: z.optional(z.boolean()).default(false),
    de_end_time: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    bv_end_time: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    sd_end_time: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    id: z.int(),
    player_id: z.int()
});

/**
 * BaseCTAppInfo
 *
 * base model for cursed technique application info, without "ct_id", "ct"
 *
 * id: int
 * number: int
 */
export const zBaseCtAppInfo = z.object({
    name: z.string().min(3).max(100),
    application: z.string().min(100).max(500),
    id: z.int(),
    number: z.int()
});

/**
 * BaseCTInfo
 *
 * base model for ct info, without player info
 *
 * id: int
 * applications: list["BaseCTAppInfo"]
 */
export const zBaseCtInfo = z.object({
    name: z.string().min(3).max(100),
    definition: z.string().min(50).max(500),
    id: z.int(),
    applications: z.array(zBaseCtAppInfo)
});

/**
 * BaseVoteInfo
 *
 * #### Base vote info: Inherits from `BaseVote`
 *
 * `user_id: int = Field(description='the id of the user that casted their votes')`
 *
 * `point: float = Field(description="the point a vote carries")`
 */
export const zBaseVoteInfo = z.object({
    player_id: z.int(),
    ct_app_id: z.int(),
    id: z.int(),
    user_id: z.union([
        z.int(),
        z.null()
    ]),
    point: z.number(),
    has_been_added: z.optional(z.boolean()).default(false)
});

/**
 * Body_create_token
 */
export const zBodyCreateToken = z.object({
    grant_type: z.optional(z.union([
        z.string().regex(/password/),
        z.null()
    ])),
    username: z.string(),
    password: z.string(),
    scope: z.optional(z.string()).default(''),
    client_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    client_secret: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Body_refresh_token
 */
export const zBodyRefreshToken = z.object({
    refresh_token: z.string()
});

/**
 * Body_verify_token
 */
export const zBodyVerifyToken = z.object({
    token: z.string()
});

/**
 * CastVote
 *
 * model for collecting data to cast a vote
 */
export const zCastVote = z.object({
    player_id: z.int(),
    ct_app_id: z.int()
});

/**
 * ClientVoteInfo
 *
 * Represents information about a client's vote in a match.
 *
 * Attributes:
 * message (str): A message associated with the client's vote.
 * votes (list[BaseVoteInfo]): A list of vote information objects related to the client.
 */
export const zClientVoteInfo = z.object({
    message: z.string(),
    extra_info: z.record(z.string(), z.unknown()),
    votes: z.array(zBaseVoteInfo)
});

/**
 * Country
 */
export const zCountry = z.enum([
    'AF',
    'AL',
    'DZ',
    'AD',
    'AO',
    'AG',
    'AR',
    'AM',
    'AU',
    'AT',
    'AZ',
    'BS',
    'BH',
    'BD',
    'BB',
    'BY',
    'BE',
    'BZ',
    'BJ',
    'BT',
    'BO',
    'BA',
    'BW',
    'BR',
    'BN',
    'BG',
    'BF',
    'BI',
    'CV',
    'KH',
    'CM',
    'CA',
    'CF',
    'TD',
    'CL',
    'CN',
    'CO',
    'KM',
    'CG',
    'CD',
    'CR',
    'HR',
    'CU',
    'CY',
    'CZ',
    'DK',
    'DJ',
    'DM',
    'DO',
    'EC',
    'EG',
    'SV',
    'GQ',
    'ER',
    'EE',
    'SZ',
    'ET',
    'FJ',
    'FI',
    'FR',
    'GA',
    'GM',
    'GE',
    'DE',
    'GH',
    'GR',
    'GD',
    'GT',
    'GN',
    'GW',
    'GY',
    'HT',
    'HN',
    'HU',
    'IS',
    'IN',
    'ID',
    'IR',
    'IQ',
    'IE',
    'IL',
    'IT',
    'JM',
    'JP',
    'JO',
    'KZ',
    'KE',
    'KI',
    'XK',
    'KW',
    'KG',
    'LA',
    'LV',
    'LB',
    'LS',
    'LR',
    'LY',
    'LI',
    'LT',
    'LU',
    'MG',
    'MW',
    'MY',
    'MV',
    'ML',
    'MT',
    'MH',
    'MR',
    'MU',
    'MX',
    'FM',
    'MD',
    'MC',
    'MN',
    'ME',
    'MA',
    'MZ',
    'MM',
    'NA',
    'NR',
    'NP',
    'NL',
    'NZ',
    'NI',
    'NE',
    'NG',
    'KP',
    'MK',
    'NO',
    'OM',
    'PK',
    'PW',
    'PS',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'QA',
    'RO',
    'RU',
    'RW',
    'KN',
    'LC',
    'VC',
    'WS',
    'SM',
    'ST',
    'SA',
    'SN',
    'RS',
    'SC',
    'SL',
    'SG',
    'SK',
    'SI',
    'SB',
    'SO',
    'ZA',
    'KR',
    'SS',
    'ES',
    'LK',
    'SD',
    'SR',
    'SE',
    'CH',
    'SY',
    'TW',
    'TJ',
    'TZ',
    'TH',
    'TL',
    'TG',
    'TO',
    'TT',
    'TN',
    'TR',
    'TM',
    'TV',
    'UG',
    'UA',
    'AE',
    'GB',
    'US',
    'UY',
    'UZ',
    'VU',
    'VA',
    'VE',
    'VN',
    'YE',
    'ZM',
    'ZW'
]);

/**
 * BaseColonyInfo
 *
 * base colony info without matches
 *
 * id: int
 */
export const zBaseColonyInfo = z.object({
    country: zCountry,
    id: z.int()
});

/**
 * BaseUserInfo
 *
 * Base model for user info, without player info
 *
 * `id: int`
 *
 * `created: date`
 */
export const zBaseUserInfo = z.object({
    username: z.string().min(4).regex(/^[A-Za-z][A-Za-z0-9_-]{2,19}$/),
    email: z.email(),
    country: z.optional(z.union([
        zCountry,
        z.null()
    ])),
    is_verified: z.optional(z.boolean()).default(false),
    id: z.int(),
    created: z.iso.date()
});

/**
 * CreateCT
 *
 * for creating cursed technique
 */
export const zCreateCt = z.object({
    name: z.string().min(3).max(100),
    definition: z.string().min(50).max(500)
});

/**
 * CreateCTApp
 *
 * for creating a cursed technique application
 */
export const zCreateCtApp = z.object({
    name: z.string().min(3).max(100),
    application: z.string().min(100).max(500)
});

/**
 * CreateUser
 *
 * For creating a user
 */
export const zCreateUser = z.object({
    username: z.string().min(4).regex(/^[A-Za-z][A-Za-z0-9_-]{2,19}$/),
    email: z.email(),
    country: z.optional(z.union([
        zCountry,
        z.null()
    ])),
    is_verified: z.optional(z.boolean()).default(false),
    password: z.string(),
    confirm_password: z.string()
});

/**
 * EditCT
 *
 * for editing a cursed technique
 */
export const zEditCt = z.object({
    name: z.optional(z.union([
        z.string().min(3).max(100),
        z.null()
    ])),
    definition: z.optional(z.union([
        z.string().min(50).max(500),
        z.null()
    ]))
});

/**
 * EditCTApp
 *
 * for editing a cursed technique application
 */
export const zEditCtApp = z.object({
    number: z.int().gte(1).lte(5),
    name: z.optional(z.union([
        z.string().min(3).max(100),
        z.null()
    ])),
    application: z.optional(z.union([
        z.string().min(100).max(500),
        z.null()
    ]))
});

/**
 * EditUser
 *
 * For editing a User
 */
export const zEditUser = z.object({
    username: z.optional(z.union([
        z.string().regex(/^[A-Za-z][A-Za-z0-9_-]{2,19}$/),
        z.null()
    ])),
    email: z.optional(z.union([
        z.email(),
        z.null()
    ])),
    country: z.optional(z.union([
        zCountry,
        z.null()
    ]))
});

/**
 * Gender
 *
 * the player gender options
 */
export const zGender = z.enum([
    'male',
    'female',
    'non-binary'
]);

/**
 * CreatePlayer
 *
 * For creating a Player
 */
export const zCreatePlayer = z.object({
    name: z.string().min(4).max(50),
    gender: zGender,
    age: z.int().gte(10).lte(102),
    role: z.optional(z.union([
        z.string().min(3).max(50),
        z.null()
    ])),
    picture: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Body_create_player
 */
export const zBodyCreatePlayer = z.object({
    player: zCreatePlayer,
    cursed_technique: zCreateCt,
    applications: z.tuple([
        zCreateCtApp,
        zCreateCtApp,
        zCreateCtApp,
        zCreateCtApp,
        zCreateCtApp
    ])
});

/**
 * EditPlayer
 *
 * For editing a Player
 */
export const zEditPlayer = z.object({
    name: z.optional(z.union([
        z.string().min(2).max(50),
        z.null()
    ])),
    gender: z.optional(z.union([
        zGender,
        z.null()
    ])),
    age: z.optional(z.union([
        z.int().gte(10).lte(102),
        z.null()
    ])),
    role: z.optional(z.union([
        z.string().min(3).max(50),
        z.null()
    ])),
    picture: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Body_admin_edit_player
 */
export const zBodyAdminEditPlayer = z.object({
    player: z.optional(z.union([
        zEditPlayer,
        z.null()
    ])),
    cursed_technique: z.optional(z.union([
        zEditCt,
        z.null()
    ])),
    applications: z.optional(z.union([
        z.array(zEditCtApp).max(5),
        z.null()
    ]))
});

/**
 * Body_edit_player
 */
export const zBodyEditPlayer = z.object({
    player: z.optional(z.union([
        zEditPlayer,
        z.null()
    ])),
    cursed_technique: z.optional(z.union([
        zEditCt,
        z.null()
    ])),
    applications: z.optional(z.union([
        z.array(zEditCtApp).max(5),
        z.null()
    ]))
});

/**
 * Grade
 *
 * the enum class for player grades
 */
export const zGrade = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4)
]);

/**
 * BasePlayerInfo
 *
 * Base model for player info, without cursed technique info and user info
 *
 * `id: int`
 *
 * `created: date`
 *
 * `grade: BasePlayer.Grade`
 *
 * `points: Decimal`
 */
export const zBasePlayerInfo = z.object({
    name: z.string().min(4).max(50),
    gender: zGender,
    age: z.int().gte(10).lte(102),
    role: z.optional(z.union([
        z.string().min(3).max(50),
        z.null()
    ])),
    picture: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    id: z.int(),
    created: z.iso.date(),
    grade: zGrade,
    points: z.number(),
    alive: z.boolean()
});

/**
 * BaseMatchInfo
 *
 * base match info with the `winner`, but without players and colony infos.
 *
 * `id: int`
 *
 * `winner: Union[BasePlayerInfo, None]`
 */
export const zBaseMatchInfo = z.object({
    begin: z.iso.datetime(),
    end: z.iso.datetime(),
    part: z.int(),
    draw: z.optional(z.boolean()).default(false),
    id: z.int(),
    winner: z.union([
        zBasePlayerInfo,
        z.null()
    ])
});

/**
 * ColonyInfo
 *
 * colony info -> client-side
 */
export const zColonyInfo = z.object({
    country: zCountry,
    id: z.int(),
    players: z.array(zBasePlayerInfo)
});

/**
 * MatchInfo
 *
 * match info for client side
 */
export const zMatchInfo = z.object({
    begin: z.iso.datetime(),
    end: z.iso.datetime(),
    part: z.int(),
    draw: z.optional(z.boolean()).default(false),
    id: z.int(),
    winner: z.union([
        zBasePlayerInfo,
        z.null()
    ]),
    players: z.array(zBasePlayerInfo),
    colony: zBaseColonyInfo,
    votes: z.array(zBaseVoteInfo),
    barrier_records: z.array(zBarrierRecordInfo)
});

/**
 * ModelName
 *
 * class for the enum of database table names.
 */
export const zModelName = z.enum([
    'admin',
    'permission',
    'barriertech',
    'barrierrecord',
    'colony',
    'match',
    'vote',
    'player',
    'cursedtechnique',
    'ctapp',
    'user'
]);

/**
 * PermissionLevel
 */
export const zPermissionLevel = z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4)
]);

/**
 * BasePermissionInfo
 *
 * base permission data, without id
 *
 * `name: str = Field(description="Permission name")`
 *
 * `level: BasePermission.PermissionLevel`
 */
export const zBasePermissionInfo = z.object({
    model: zModelName,
    id: z.int(),
    name: z.string(),
    level: zPermissionLevel
});

/**
 * AdminInfo
 *
 * the admin info for client side
 */
export const zAdminInfo = z.object({
    id: z.uuid(),
    is_superuser: z.boolean(),
    permissions: z.array(zBasePermissionInfo),
    user: zBaseUserInfo
});

/**
 * BaseAdminInfo
 *
 * base admin info without the user info
 *
 * `is_superuser: bool | None`
 *
 * `permissions: list[BasePermissionInfo]`
 */
export const zBaseAdminInfo = z.object({
    id: z.uuid(),
    is_superuser: z.boolean(),
    permissions: z.array(zBasePermissionInfo)
});

/**
 * PermissionInfo
 */
export const zPermissionInfo = z.object({
    model: zModelName,
    id: z.int(),
    name: z.string(),
    level: zPermissionLevel
});

/**
 * PermissionRequest
 *
 * Model for collecting A Permission request
 */
export const zPermissionRequest = z.object({
    model: zModelName,
    levels: z.array(zPermissionLevel)
});

/**
 * PlayerInfo
 *
 * Player info with cursed technique, user, and colony info
 */
export const zPlayerInfo = z.object({
    name: z.string().min(4).max(50),
    gender: zGender,
    age: z.int().gte(10).lte(102),
    role: z.optional(z.union([
        z.string().min(3).max(50),
        z.null()
    ])),
    picture: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    id: z.int(),
    created: z.iso.date(),
    grade: zGrade,
    points: z.number(),
    alive: z.boolean(),
    cursed_technique: zBaseCtInfo,
    barrier_technique: z.union([
        zBarrierTechInfo,
        z.null()
    ]),
    colony: z.union([
        zBaseColonyInfo,
        z.null()
    ]),
    user: z.union([
        zBaseUserInfo,
        z.null()
    ]),
    matches: z.array(zBaseMatchInfo),
    votes: z.array(zBaseVoteInfo)
});

/**
 * Token
 *
 * model for encoded access token, resfresh token,
 * and acces token expires time
 */
export const zToken = z.object({
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.string(),
    expires_in: z.int(),
    refresh_expires_in: z.int()
});

/**
 * TokenData
 *
 * response model for decoded token
 */
export const zTokenData = z.object({
    data: z.record(z.string(), z.unknown()),
    refresh_token_key: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    exp: z.iso.datetime(),
    iat: z.iso.datetime(),
    scopes: z.optional(z.array(z.string())).default([])
});

/**
 * UserInfo
 *
 * The user info
 */
export const zUserInfo = z.object({
    username: z.string().min(4).regex(/^[A-Za-z][A-Za-z0-9_-]{2,19}$/),
    email: z.email(),
    country: z.optional(z.union([
        zCountry,
        z.null()
    ])),
    is_verified: z.optional(z.boolean()).default(false),
    id: z.int(),
    created: z.iso.date(),
    player: z.optional(z.union([
        zBasePlayerInfo,
        z.null()
    ])),
    admin: z.optional(z.union([
        zBaseAdminInfo,
        z.null()
    ]))
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

/**
 * VerifyUserOut
 *
 * schema for response of verify user route
 */
export const zVerifyUserOut = z.object({
    message: z.string()
});

export const zCurrentUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A User
 */
export const zCurrentUserResponse = zUserInfo;

export const zAUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user: z.union([
            z.int(),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * A User
 */
export const zAUserResponse = zUserInfo;

export const zEditUserData = z.object({
    body: zEditUser,
    path: z.object({
        user: z.union([
            z.int(),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Edited User
 */
export const zEditUserResponse = zUserInfo;

export const zDeleteUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user: z.union([
            z.int(),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Deleted User
 */
export const zDeleteUserResponse = zUserInfo;

export const zVerifyUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        token: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }))
});

/**
 * Verification Token Sent
 */
export const zVerifyUserResponse = zVerifyUserOut;

export const zCreatePlayerData = z.object({
    body: zBodyCreatePlayer,
    path: z.object({
        user: z.union([
            z.int(),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * New Player
 */
export const zCreatePlayerResponse = zPlayerInfo;

export const zMyPlayerData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A Player
 */
export const zMyPlayerResponse = zPlayerInfo;

export const zGetPlayersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        offset: z.optional(z.int().gte(0)).default(0),
        limit: z.optional(z.int().lte(30)).default(10),
        slim: z.optional(z.boolean()).default(false),
        gender: z.optional(z.union([
            zGender,
            z.null()
        ])),
        age: z.optional(z.union([
            z.int().gte(10).lte(102),
            z.null()
        ])),
        role: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        alive: z.optional(z.boolean()).default(true)
    }))
});

/**
 * Response Get Players
 *
 * A list of players
 */
export const zGetPlayersResponse = z.union([
    z.array(zPlayerInfo),
    z.array(zBasePlayerInfo)
]);

export const zAPlayerData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        player_id: z.int()
    }),
    query: z.optional(z.object({
        alive: z.optional(z.boolean()).default(true)
    }))
});

/**
 * A Player
 */
export const zAPlayerResponse = zPlayerInfo;

export const zEditPlayerData = z.object({
    body: z.optional(zBodyEditPlayer),
    path: z.object({
        player_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Edited Player
 */
export const zEditPlayerResponse = zPlayerInfo;

export const zDeletePlayerData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        player_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * A deleted player
 */
export const zDeletePlayerResponse = zPlayerInfo;

export const zUpgradePlayerData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        player_id: z.int()
    }),
    query: z.object({
        grade_up: zGrade
    })
});

/**
 * Successful Response
 */
export const zUpgradePlayerResponse = zPlayerInfo;

export const zVoteData = z.object({
    body: z.array(zCastVote).min(1).max(5),
    path: z.object({
        match_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zVoteResponse = zClientVoteInfo;

export const zCreateMatchData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        part: z.int()
    })
});

/**
 * Successful Response
 */
export const zCreateMatchResponse = zMatchInfo;

export const zGetMatchesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        offset: z.optional(z.int().gte(0)).default(0),
        limit: z.optional(z.int().lte(30)).default(10)
    }))
});

/**
 * Response Get Matches
 *
 * Successful Response
 */
export const zGetMatchesResponse = z.array(zMatchInfo);

export const zGetLastestMatchData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        ongoing: z.optional(z.boolean()).default(false)
    }))
});

/**
 * Successful Response
 */
export const zGetLastestMatchResponse = zMatchInfo;

export const zDeleteMatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        match_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDeleteMatchResponse = zMatchInfo;

export const zAssignMatchWinnerData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        match_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAssignMatchWinnerResponse = zMatchInfo;

export const zDomainExpansionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        player_id: z.int(),
        match_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDomainExpansionResponse = zBarrierTechInfo;

export const zSimpleDomainData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        player_id: z.int(),
        match_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zSimpleDomainResponse = zBarrierTechInfo;

export const zBindindVowData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        player_id: z.int(),
        match_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zBindindVowResponse = zBarrierTechInfo;

export const zReverseCursedTechniqueData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        player_id: z.int(),
        match_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zReverseCursedTechniqueResponse = zBarrierTechInfo;

export const zDeactivateDomainExpansionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        player_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDeactivateDomainExpansionResponse = zBarrierTechInfo;

export const zGetColoniesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        offset: z.optional(z.int().gte(0)).default(0),
        limit: z.optional(z.int().lte(30)).default(10)
    }))
});

/**
 * Response Get Colonies
 *
 * Successful Response
 */
export const zGetColoniesResponse = z.array(zColonyInfo);

export const zDemoSuperuserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user: z.union([
            z.int(),
            z.string()
        ])
    }),
    query: z.object({
        code: z.uuid()
    })
});

/**
 * Successful Response
 */
export const zDemoSuperuserResponse = zAdminInfo;

export const zAdminEditUserData = z.object({
    body: zEditUser,
    path: z.object({
        user: z.union([
            z.int(),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Edited User
 */
export const zAdminEditUserResponse = zUserInfo;

export const zAdminDeleteUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user: z.union([
            z.int(),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Deleted User
 */
export const zAdminDeleteUserResponse = zUserInfo;

export const zAdminEditPlayerData = z.object({
    body: z.optional(zBodyAdminEditPlayer),
    path: z.object({
        player_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Edited Player
 */
export const zAdminEditPlayerResponse = zPlayerInfo;

export const zAdminDeletePlayerData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        player_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * A deleted player
 */
export const zAdminDeletePlayerResponse = zPlayerInfo;

export const zCreateAdminData = z.object({
    body: z.array(zPermissionRequest),
    path: z.object({
        user: z.union([
            z.int(),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zCreateAdminResponse = zAdminInfo;

export const zNewPermissionData = z.object({
    body: z.array(zPermissionRequest),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response New Permission
 *
 * Successful Response
 */
export const zNewPermissionResponse = z.array(zPermissionInfo);

export const zGrantPermissionData = z.object({
    body: z.array(zPermissionRequest),
    path: z.object({
        admin_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGrantPermissionResponse = zAdminInfo;

export const zRemovePermissionData = z.object({
    body: z.array(zPermissionRequest),
    path: z.object({
        admin_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zRemovePermissionResponse = zAdminInfo;

export const zCurrentAdminData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * An Admin
 */
export const zCurrentAdminResponse = zAdminInfo;

export const zCreateTokenData = z.object({
    body: zBodyCreateToken,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A Token
 */
export const zCreateTokenResponse = zToken;

export const zRefreshTokenData = z.object({
    body: zBodyRefreshToken,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * An Updated Token
 */
export const zRefreshTokenResponse = zToken;

export const zVerifyTokenData = z.object({
    body: zBodyVerifyToken,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A Verified Token
 */
export const zVerifyTokenResponse = zTokenData;

export const zCreateUserData = z.object({
    body: zCreateUser,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * New User
 */
export const zCreateUserResponse = zUserInfo;

export const zHomePageData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zHomePageResponse = z.string();
