// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import "@mantine/charts/styles.css";
import "@mantine/core/styles.layer.css";
import "@mantine/notifications/styles.css";
import "@mantine/nprogress/styles.css";

import {
    ColorSchemeScript,
    DEFAULT_THEME,
    MantineProvider,
    createTheme,
    mantineHtmlProps,
    rem,
} from "@mantine/core";

import { Notifications } from "@mantine/notifications";

import { charcoalColor, deepRedColor, goldColor } from "@/lib/constants/themes";

import TanstackProviders from "@/lib/query-client/providers";

import Naluka from "@/fonts/NalukaFont";
import Neuropol from "@/fonts/NeuropolFont";
import Nexarust from "@/fonts/NexarustFont";

import { RouterTransition } from "@/components/ui/router-transition";
import { ShellApp } from "@/components/ui/shell/shell-app";
import { ShellContextProvider } from "@/lib/contexts/shell-context-provider";
import { SocketContextProvider } from "@/lib/contexts/socket-context-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "The Culling Games",
    description: "Generated by create next app",
};

const theme = createTheme({
    autoContrast: true,
    colors: {
        gold: goldColor,
        deepred: deepRedColor,
        charcoal: charcoalColor,
    },
    primaryColor: "gold",
    fontFamily: `${Neuropol.style.fontFamily}, ${Nexarust.style.fontFamily}, ${DEFAULT_THEME.fontFamily}`,
    headings: {
        fontFamily: `${Nexarust.style.fontFamily}, ${Naluka.style.fontFamily}, ${DEFAULT_THEME.fontFamily}`,
    },
    fontSizes: {
        xs: rem(10),
        sm: rem(11),
        md: rem(14),
        lg: rem(16),
        xl: rem(20),
    },
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body>
                <MantineProvider theme={theme}>
                    <RouterTransition />
                    <Notifications />
                    <TanstackProviders>
                        <SocketContextProvider
                            serverUrl={
                                process.env.NODE_ENV === "production"
                                    ? "https://the-culling-games.up.railway.app"
                                    : "http://localhost:8000"
                            }
                            socketPath="/ws"
                        >
                            <ShellContextProvider>
                                <ShellApp>{children}</ShellApp>
                            </ShellContextProvider>
                        </SocketContextProvider>
                    </TanstackProviders>
                </MantineProvider>
            </body>
        </html>
    );
}

export const runtime = "edge";
