// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import "@mantine/charts/styles.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/nprogress/styles.css";

import {
    ColorSchemeScript,
    Container,
    DEFAULT_THEME,
    MantineProvider,
    createTheme,
    mantineHtmlProps,
    rem,
} from "@mantine/core";

import { NavigationProgress } from "@mantine/nprogress";

import { Notifications } from "@mantine/notifications";

import TanstackProviders from "@/lib/query-client/providers";

import {
    charcoalColor,
    deepRedColor,
    goldColor,
} from "@/lib/constants/themeColors";

import Naluka from "@/fonts/NalukaFont";
import Neuropol from "@/fonts/NeuropolFont";
import Nexarust from "@/fonts/NexarustFont";

import { ModeToggle } from "@/components/ui/mode-toggle";

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "The Culling Games",
    description: "Generated by create next app",
};

const theme = createTheme({
    autoContrast: true,
    colors: {
        gold: goldColor,
        deepred: deepRedColor,
        charcoal: charcoalColor,
    },
    primaryColor: "gold",
    fontFamily: `${Neuropol.style.fontFamily}, ${Nexarust.style.fontFamily}, ${DEFAULT_THEME.fontFamily}`,
    headings: {
        fontFamily: `${Nexarust.style.fontFamily}, ${Naluka.style.fontFamily}, ${DEFAULT_THEME.fontFamily}`,
    },
    fontSizes: {
        xs: rem(10),
        sm: rem(11),
        md: rem(14),
        lg: rem(16),
        xl: rem(20),
    },
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body>
                <TanstackProviders>
                    <MantineProvider theme={theme}>
                        <NavigationProgress />
                        <Notifications />
                        <Container size={"lg"}>
                            <ModeToggle />
                            {children}
                        </Container>
                    </MantineProvider>
                </TanstackProviders>
            </body>
        </html>
    );
}
