// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import "@mantine/charts/styles.css";
import "@mantine/core/styles.css";

import {
    ColorSchemeScript,
    Container,
    DEFAULT_THEME,
    MantineProvider,
    createTheme,
    mantineHtmlProps,
    rem,
} from "@mantine/core";

import {
    charcoalColor,
    deepRedColor,
    goldColor,
} from "@/lib/constants/themeColors";

import Naluka from "@/fonts/NalukaFont";
import Neuropol from "@/fonts/NeuropolFont";

import { ModeToggle } from "@/components/ui/mode-toggle";

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "The Culling Games",
    description: "Generated by create next app",
};

const theme = createTheme({
    autoContrast: true,
    colors: {
        gold: goldColor,
        deepred: deepRedColor,
        charcoal: charcoalColor,
    },
    primaryColor: "deepred",
    fontFamily: `${Neuropol.style.fontFamily}, ${DEFAULT_THEME.fontFamily}`,
    headings: {
        fontFamily: `${Naluka.style.fontFamily}, ${DEFAULT_THEME.fontFamily}`,
    },
    fontSizes: {
        xs: rem(10),
        sm: rem(11),
        md: rem(14),
        lg: rem(16),
        xl: rem(20),
    },
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body>
                <MantineProvider theme={theme}>
                    <Container size={"lg"} my={40}>
                        <ModeToggle />
                        {children}
                    </Container>
                </MantineProvider>
            </body>
        </html>
    );
}
