import { Header } from "@/components/shell/Header";
import { TanQueryProvider } from "@/components/shell/TanQueryProvider";
import { ThemeProvider } from "@/components/shell/theme-povider";
import { Toaster } from "@/components/ui/sonner";
import { inter } from "@/fonts/googleFonts";
import "@/styles/global.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "The Culling Games",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>
                <ThemeProvider
                    attribute={"class"}
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />
                    <main className="w-full min-h-screen border pt-[60px] bg-gradient-radial dark:from-slate-400 dark:to-slate-900 to-slate-400 from-slate-900">
                        <TanQueryProvider>{children}</TanQueryProvider>
                    </main>
                    <Toaster position="top-right" />
                </ThemeProvider>
            </body>
        </html>
    );
}
