name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Generate ModelName enum
        run: python app/scripts/gen_table_enum.py

      - name: Run migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest
