// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-next';
import type { CurrentUserData, CurrentUserResponse, AuserData, AuserResponse, AuserError, EditUserData, EditUserResponse, EditUserError, DeleteUserData, DeleteUserResponse, DeleteUserError, CreatePlayerData, CreatePlayerResponse, CreatePlayerError, MyPlayerData, MyPlayerResponse, GetPlayersData, GetPlayersResponse, GetPlayersError, APlayerData, APlayerResponse, APlayerError, EditPlayerData, EditPlayerResponse, EditPlayerError, DeletePlayerData, DeletePlayerResponse, DeletePlayerError, UpgradePlayerData, UpgradePlayerResponse, UpgradePlayerError, VoteData, VoteResponse, VoteError, CreateMatchData, CreateMatchResponse, CreateMatchError, GetMatchesData, GetMatchesResponse, GetMatchesError, GetLastestMatchData, GetLastestMatchResponse, GetLastestMatchError, DeleteMatchData, DeleteMatchError, DomainExpansionData, DomainExpansionResponse, DomainExpansionError, SimpleDomainData, SimpleDomainResponse, SimpleDomainError, BindindVowData, BindindVowResponse, BindindVowError, ReverseCursedTechniqueData, ReverseCursedTechniqueResponse, ReverseCursedTechniqueError, GetColoniesData, GetColoniesResponse, GetColoniesError, DemoSuperuserData, DemoSuperuserError, AdminEditUserData, AdminEditUserResponse, AdminEditUserError, AdminDeleteUserData, AdminDeleteUserResponse, AdminDeleteUserError, AdminEditPlayerData, AdminEditPlayerResponse, AdminEditPlayerError, AdminDeletePlayerData, AdminDeletePlayerResponse, AdminDeletePlayerError, CreateAdminData, CreateAdminResponse, CreateAdminError, NewPermissionData, NewPermissionResponse, NewPermissionError, GrantPermissionData, GrantPermissionResponse, GrantPermissionError, RemovePermissionData, RemovePermissionResponse, RemovePermissionError, CreateTokenData, CreateTokenResponse, CreateTokenError, RefreshTokenData, RefreshTokenResponse, RefreshTokenError, VerifyTokenData, VerifyTokenResponse, VerifyTokenError, CreateUserData, CreateUserResponse, CreateUserError, ChatHtmlData, ChatHtmlResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UsersService {
    /**
     * Get the logged in user
     */
    public static currentUser<ThrowOnError extends boolean = false>(options?: Options<CurrentUserData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<CurrentUserResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/users/me',
            ...options
        });
    }
    
    /**
     * Get a user.
     */
    public static aUser<ThrowOnError extends boolean = false>(options: Options<AuserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<AuserResponse, AuserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/users/{user}',
            ...options
        });
    }
    
    /**
     * Edit a user.
     */
    public static editUser<ThrowOnError extends boolean = false>(options: Options<EditUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<EditUserResponse, EditUserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/users/edit/{user}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete a user.
     * Deleting a user will _set null_ on the *player* if any.
     */
    public static deleteUser<ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteUserResponse, DeleteUserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/users/delete/{user}',
            ...options
        });
    }
    
    /**
     * Create a new User
     */
    public static createUser<ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateUserResponse, CreateUserError, ThrowOnError>({
            url: '/signup',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class PlayersService {
    /**
     * Create a new player
     */
    public static createPlayer<ThrowOnError extends boolean = false>(options: Options<CreatePlayerData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreatePlayerResponse, CreatePlayerError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/player/create/{user}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Get a player of the logged in user
     */
    public static myPlayer<ThrowOnError extends boolean = false>(options?: Options<MyPlayerData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<MyPlayerResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/player/me',
            ...options
        });
    }
    
    /**
     * Get a list of players.
     */
    public static getPlayers<ThrowOnError extends boolean = false>(options?: Options<GetPlayersData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetPlayersResponse, GetPlayersError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/player/all',
            ...options
        });
    }
    
    /**
     * Get a player with their ID
     */
    public static aPlayer<ThrowOnError extends boolean = false>(options: Options<APlayerData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<APlayerResponse, APlayerError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/player/{player_id}',
            ...options
        });
    }
    
    /**
     * Edit a player details.
     * If an application is sent, it should have a valid number for the application you want to edit.
     *
     * To check an application number, first get a player info using the **'/players/{player_id}'** request.
     *
     * Else the application will be disregarded, valid numbers are 1-5.
     */
    public static editPlayer<ThrowOnError extends boolean = false>(options: Options<EditPlayerData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<EditPlayerResponse, EditPlayerError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/player/edit/{player_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete a player
     */
    public static deletePlayer<ThrowOnError extends boolean = false>(options: Options<DeletePlayerData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeletePlayerResponse, DeletePlayerError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/player/delete/{player_id}',
            ...options
        });
    }
    
    /**
     * Upgrade Player
     * function for uprading the grade of a player.
     *
     * **points required.**
     */
    public static upgradePlayer<ThrowOnError extends boolean = false>(options: Options<UpgradePlayerData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<UpgradePlayerResponse, UpgradePlayerError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/player/upgrade/{player_id}',
            ...options
        });
    }
    
}

export class MatchesService {
    /**
     * Vote
     * function for casting votes
     *
     * - a match id is required
     * - if an invalid vote cursed application id or player id is submitted, they are ignored.
     */
    public static vote<ThrowOnError extends boolean = false>(options: Options<VoteData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<VoteResponse, VoteError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/match/vote/{match_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Create Match
     * path operation for automatically creating a match, requires a part query.
     */
    public static createMatch<ThrowOnError extends boolean = false>(options: Options<CreateMatchData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateMatchResponse, CreateMatchError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/match/create',
            ...options
        });
    }
    
    /**
     * Get Matches
     * get all matches
     */
    public static getMatches<ThrowOnError extends boolean = false>(options?: Options<GetMatchesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetMatchesResponse, GetMatchesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/match/all',
            ...options
        });
    }
    
    /**
     * Get Lastest Match
     * get last created match
     */
    public static getLastestMatch<ThrowOnError extends boolean = false>(options?: Options<GetLastestMatchData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetLastestMatchResponse, GetLastestMatchError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/match/latest',
            ...options
        });
    }
    
    /**
     * Delete Match
     * Deletes a match from the database given its ID after verifying delete permissions.
     */
    public static deleteMatch<ThrowOnError extends boolean = false>(options: Options<DeleteMatchData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<unknown, DeleteMatchError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/match/delete/{match_id}',
            ...options
        });
    }
    
}

export class BarriersService {
    /**
     * Domain Expansion
     * Activates the domain of a player in an ongoing match.
     *
     * Buffs the vote to x4 per vote.
     *
     * Weakend by simple domain
     */
    public static domainExpansion<ThrowOnError extends boolean = false>(options: Options<DomainExpansionData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<DomainExpansionResponse, DomainExpansionError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/barrier/activate/domain/{player_id}',
            ...options
        });
    }
    
    /**
     * Simple Domain
     * Activates the simple domain effect for a player during an ongoing match. The simple domain interaction
     * modifies the opponent's capabilities based on their current domain status:
     * - If the opponent's domain expansion is inactive, it halves the effect of their opponent's votes per action.
     * - If the domain expansion is active, it weakens its effect.
     */
    public static simpleDomain<ThrowOnError extends boolean = false>(options: Options<SimpleDomainData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<SimpleDomainResponse, SimpleDomainError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/barrier/activate/simple/{player_id}',
            ...options
        });
    }
    
    /**
     * Bindind Vow
     * activates a binding vow
     */
    public static bindindVow<ThrowOnError extends boolean = false>(options: Options<BindindVowData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<BindindVowResponse, BindindVowError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/barrier/activate/binding/{player_id}',
            ...options
        });
    }
    
    /**
     * Reverse Cursed Technique
     * activates a reverse cursed technique
     */
    public static reverseCursedTechnique<ThrowOnError extends boolean = false>(options: Options<ReverseCursedTechniqueData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ReverseCursedTechniqueResponse, ReverseCursedTechniqueError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/barrier/activate/rct/{player_id}',
            ...options
        });
    }
    
}

export class ColoniesService {
    /**
     * Get Colonies
     * get all matches
     */
    public static getColonies<ThrowOnError extends boolean = false>(options?: Options<GetColoniesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetColoniesResponse, GetColoniesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/colony/all',
            ...options
        });
    }
    
}

export class AdminsService {
    /**
     * Demo Superuser
     */
    public static demoSuperuser<ThrowOnError extends boolean = false>(options: Options<DemoSuperuserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, DemoSuperuserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/admin/superuser/{user}',
            ...options
        });
    }
    
    /**
     * Admin Operation to Edit a USer
     */
    public static adminEditUser<ThrowOnError extends boolean = false>(options: Options<AdminEditUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<AdminEditUserResponse, AdminEditUserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/admin/edit-user/{user}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Admin Operation to Delete a USer
     */
    public static adminDeleteUser<ThrowOnError extends boolean = false>(options: Options<AdminDeleteUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<AdminDeleteUserResponse, AdminDeleteUserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/admin/delete-user/{user}',
            ...options
        });
    }
    
    /**
     * Admin editing a player details.
     * admin api for editing a plauyer
     */
    public static adminEditPlayer<ThrowOnError extends boolean = false>(options: Options<AdminEditPlayerData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<AdminEditPlayerResponse, AdminEditPlayerError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/admin/edit-player',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Admin deletion of a player
     * API for admin deletion of a player
     */
    public static adminDeletePlayer<ThrowOnError extends boolean = false>(options: Options<AdminDeletePlayerData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<AdminDeletePlayerResponse, AdminDeletePlayerError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/admin/delete-player',
            ...options
        });
    }
    
    /**
     * Create Admin
     * Creates an admin user with specified permissions.
     */
    public static createAdmin<ThrowOnError extends boolean = false>(options: Options<CreateAdminData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateAdminResponse, CreateAdminError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/admin/create/{user}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * New Permission
     * for creating new permissions; only doable by a superuser
     */
    public static newPermission<ThrowOnError extends boolean = false>(options: Options<NewPermissionData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<NewPermissionResponse, NewPermissionError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/admin/new-permission',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Grant Permission
     */
    public static grantPermission<ThrowOnError extends boolean = false>(options: Options<GrantPermissionData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<GrantPermissionResponse, GrantPermissionError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/admin/grant-permission/{user}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Remove Permission
     * remove permission(s) of an admin. A superuser is required
     */
    public static removePermission<ThrowOnError extends boolean = false>(options: Options<RemovePermissionData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<RemovePermissionResponse, RemovePermissionError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/admin/remove-permission/{user}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class AuthService {
    /**
     * creates a login token
     */
    public static createToken<ThrowOnError extends boolean = false>(options: Options<CreateTokenData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateTokenResponse, CreateTokenError, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            url: '/login',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * refreshes/updates a token
     */
    public static refreshToken<ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<RefreshTokenResponse, RefreshTokenError, ThrowOnError>({
            url: '/refresh-token',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * verifies a token
     * Verifies the JWT in `token` and returns its decoded payload:
     * - `sub`: the subject (usually user ID)
     * - `exp`: expiration timestamp
     * - `iat`: issued-at timestamp
     * - `scopes`: optional list of permission scopes
     */
    public static verifyToken<ThrowOnError extends boolean = false>(options: Options<VerifyTokenData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<VerifyTokenResponse, VerifyTokenError, ThrowOnError>({
            url: '/verify-token',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class DefaultService {
    /**
     * Chat Html
     */
    public static chatHtml<ThrowOnError extends boolean = false>(options?: Options<ChatHtmlData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<ChatHtmlResponse, unknown, ThrowOnError>({
            url: '/',
            ...options
        });
    }
    
}