// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AdminInfo
 *
 * the admin info for client side
 */
export type AdminInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Permissions
     */
    permissions: Array<BasePermissionInfo>;
    user: BaseUserInfo;
};

/**
 * BarrierRecordInfo
 */
export type BarrierRecordInfo = {
    /**
     * Domain Counter
     *
     * the number of times a domain is activated
     */
    domain_counter?: number;
    /**
     * Simple Domain Counter
     *
     * the number of times a simple domain is activated
     */
    simple_domain_counter?: number;
    /**
     * Binding Vow Counter
     *
     * the number of times a binding vow is activated
     */
    binding_vow_counter?: number;
    /**
     * Reverse Cursed Technique Counter
     *
     * the number of times a reverse cursed technique is activated
     */
    reverse_cursed_technique_counter?: number;
    /**
     * Id
     */
    id: number;
    /**
     * Barrier Tech Id
     */
    barrier_tech_id: number;
    /**
     * Match Id
     */
    match_id: number;
};

/**
 * BarrierTechInfo
 *
 * Represents barrier technique information for client-side.
 *
 * Attributes:
 * id (int): Unique identifier for the barrier technique.
 * player_id: int
 * domain_expansion: bool = Field(default=False, description="the player's domain expansion")
 * binding_vow: bool = Field(default=False, description="the player's binding vow")
 * simple_domain: bool = Field(default=False, description="the player's simple domain")
 * The times are useful for know when to activate/deactivate the techniques
 * de_end_time: datetime | None = Field(default=None, description="the time a player cast their domain")
 * bv_end_time: datetime | None = Field(default=None, description="the time a player cast their binding_vow")
 * sd_end_time: datetime | None = Field(default=None, description="the time a player cast their simple_domain")
 */
export type BarrierTechInfo = {
    /**
     * Domain Expansion
     *
     * the player's domain expansion
     */
    domain_expansion?: boolean;
    /**
     * Binding Vow
     *
     * the player's binding vow
     */
    binding_vow?: boolean;
    /**
     * Simple Domain
     *
     * the player's simple domain
     */
    simple_domain?: boolean;
    /**
     * De End Time
     *
     * the time a player cast their domain
     */
    de_end_time?: string | null;
    /**
     * Bv End Time
     *
     * the time a player cast their binding_vow
     */
    bv_end_time?: string | null;
    /**
     * Sd End Time
     *
     * the time a player cast their simple_domain
     */
    sd_end_time?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Player Id
     */
    player_id: number;
};

/**
 * BaseAdminInfo
 *
 * base admin info without the user info
 *
 * `is_superuser: bool | None`
 * `permissions: list[BasePermissionInfo]`
 */
export type BaseAdminInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Permissions
     */
    permissions: Array<BasePermissionInfo>;
};

/**
 * BaseCTAppInfo
 *
 * base model for cursed technique application info, without "ct_id", "ct"
 *
 * id: int
 * number: int
 */
export type BaseCtAppInfo = {
    /**
     * Name
     *
     * The name of the application, must be between 3 and 100 characters
     */
    name: string;
    /**
     * Application
     *
     * The application of the cursed technique, explaining how it is used or applied in practice
     */
    application: string;
    /**
     * Id
     */
    id: number;
    /**
     * Number
     */
    number: number;
};

/**
 * BaseCTInfo
 *
 * base model for ct info, without player info
 *
 * id: int
 * applications: list["BaseCTAppInfo"]
 */
export type BaseCtInfo = {
    /**
     * Name
     *
     * The name of the cursed technique, must be between 3 and 100 characters
     */
    name: string;
    /**
     * Definition
     *
     * The definition of the cursed technique, explaining what it does without including its subsets
     */
    definition: string;
    /**
     * Id
     */
    id: number;
    /**
     * Applications
     */
    applications: Array<BaseCtAppInfo>;
};

/**
 * BaseColonyInfo
 *
 * base colony info without matches
 *
 * id: int
 */
export type BaseColonyInfo = {
    country: Country;
    /**
     * Id
     */
    id: number;
};

/**
 * BaseMatchInfo
 *
 * base match info with the `winner`, but without players and colony infos.
 *
 * `id: int`
 * `winner: Union[BasePlayerInfo, None]`
 */
export type BaseMatchInfo = {
    /**
     * Begin
     *
     * The start time of the match
     */
    begin: string;
    /**
     * End
     *
     * The end time of the match
     */
    end: string;
    /**
     * Part
     */
    part: number;
    /**
     * Draw
     *
     * whether the match was a draw
     */
    draw?: boolean;
    /**
     * Id
     */
    id: number;
    winner: BasePlayerInfo | null;
};

/**
 * BasePermissionInfo
 *
 * base permission data, without id
 *
 * `name: str = Field(description="Permission name")`
 *
 * `level: BasePermission.PermissionLevel`
 */
export type BasePermissionInfo = {
    /**
     * The model the permission applies to
     */
    model: ModelName;
    /**
     * Id
     */
    id: number;
    /**
     * Name
     *
     * Permission name
     */
    name: string;
    level: PermissionLevel;
};

/**
 * BasePlayerInfo
 *
 * Base model for player info, without cursed technique info and user info
 *
 * `id: int`
 * `created: date`
 * `grade: BasePlayer.Grade`
 * `points: Decimal`
 */
export type BasePlayerInfo = {
    /**
     * Name
     *
     * The name of the player, must be between 2 and 50 characters
     */
    name: string;
    gender: Gender;
    /**
     * Age
     */
    age: number;
    /**
     * Role
     *
     * The role of the player, e.g., doctor, lawyer, student, curse user, sorcerer etc.
     */
    role?: string | null;
    /**
     * Picture
     *
     * the picture of the player
     */
    picture?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created
     */
    created: string;
    grade: Grade;
    /**
     * Points
     */
    points: number;
    /**
     * Alive
     */
    alive: boolean;
};

/**
 * BaseUserInfo
 *
 * Base model for user info, without player info
 *
 * `id: int`
 * `created: date`
 */
export type BaseUserInfo = {
    /**
     * Username
     *
     * the username of the user
     */
    username: string;
    /**
     * Email
     *
     * the email address of the user
     */
    email: string;
    /**
     * the country of origin of the user
     */
    country?: Country | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created
     *
     * the date the account was created
     */
    created: string;
};

/**
 * BaseVoteInfo
 *
 * #### Base vote info: Inherits from `BaseVote`
 *
 * `user_id: int = Field(description='the id of the user that casted their votes')`
 * `point: float = Field(description="the point a vote carries")`
 */
export type BaseVoteInfo = {
    /**
     * Player Id
     */
    player_id: number;
    /**
     * Ct App Id
     */
    ct_app_id: number;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     *
     * the id of the user that casted their votes
     */
    user_id: number | null;
    /**
     * Point
     *
     * the point a vote carries
     */
    point: number;
    /**
     * Has Been Added
     *
     * whether or not the vote point has been added to a player's point
     */
    has_been_added?: boolean;
};

/**
 * Body_admin_edit_player
 */
export type BodyAdminEditPlayer = {
    player?: EditPlayer | null;
    cursed_technique?: EditCt | null;
    /**
     * Applications
     */
    applications?: Array<EditCtApp> | null;
};

/**
 * Body_create_player
 */
export type BodyCreatePlayer = {
    player: CreatePlayer;
    cursed_technique: CreateCt;
    /**
     * Applications
     */
    applications: [
        CreateCtApp,
        CreateCtApp,
        CreateCtApp,
        CreateCtApp,
        CreateCtApp
    ];
};

/**
 * Body_create_token
 */
export type BodyCreateToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_edit_player
 */
export type BodyEditPlayer = {
    player?: EditPlayer | null;
    cursed_technique?: EditCt | null;
    /**
     * Applications
     */
    applications?: Array<EditCtApp> | null;
};

/**
 * Body_refresh_token
 */
export type BodyRefreshToken = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * Body_verify_token
 */
export type BodyVerifyToken = {
    /**
     * Token
     */
    token: string;
};

/**
 * CastVote
 *
 * model for collecting data to cast a vote
 */
export type CastVote = {
    /**
     * Player Id
     */
    player_id: number;
    /**
     * Ct App Id
     */
    ct_app_id: number;
};

/**
 * ClientVoteInfo
 *
 * Represents information about a client's vote in a match.
 *
 * Attributes:
 * message (str): A message associated with the client's vote.
 * votes (list[BaseVoteInfo]): A list of vote information objects related to the client.
 */
export type ClientVoteInfo = {
    /**
     * Message
     */
    message: string;
    /**
     * Extra Info
     */
    extra_info: {
        [key: string]: unknown;
    };
    /**
     * Votes
     */
    votes: Array<BaseVoteInfo>;
};

/**
 * ColonyInfo
 *
 * colony info -> client-side
 */
export type ColonyInfo = {
    country: Country;
    /**
     * Id
     */
    id: number;
    /**
     * Players
     */
    players: Array<BasePlayerInfo>;
};

/**
 * Country
 */
export const Country = {
    AF: 'AF',
    AL: 'AL',
    DZ: 'DZ',
    AD: 'AD',
    AO: 'AO',
    AG: 'AG',
    AR: 'AR',
    AM: 'AM',
    AU: 'AU',
    AT: 'AT',
    AZ: 'AZ',
    BS: 'BS',
    BH: 'BH',
    BD: 'BD',
    BB: 'BB',
    BY: 'BY',
    BE: 'BE',
    BZ: 'BZ',
    BJ: 'BJ',
    BT: 'BT',
    BO: 'BO',
    BA: 'BA',
    BW: 'BW',
    BR: 'BR',
    BN: 'BN',
    BG: 'BG',
    BF: 'BF',
    BI: 'BI',
    CV: 'CV',
    KH: 'KH',
    CM: 'CM',
    CA: 'CA',
    CF: 'CF',
    TD: 'TD',
    CL: 'CL',
    CN: 'CN',
    CO: 'CO',
    KM: 'KM',
    CG: 'CG',
    CD: 'CD',
    CR: 'CR',
    HR: 'HR',
    CU: 'CU',
    CY: 'CY',
    CZ: 'CZ',
    DK: 'DK',
    DJ: 'DJ',
    DM: 'DM',
    DO: 'DO',
    EC: 'EC',
    EG: 'EG',
    SV: 'SV',
    GQ: 'GQ',
    ER: 'ER',
    EE: 'EE',
    SZ: 'SZ',
    ET: 'ET',
    FJ: 'FJ',
    FI: 'FI',
    FR: 'FR',
    GA: 'GA',
    GM: 'GM',
    GE: 'GE',
    DE: 'DE',
    GH: 'GH',
    GR: 'GR',
    GD: 'GD',
    GT: 'GT',
    GN: 'GN',
    GW: 'GW',
    GY: 'GY',
    HT: 'HT',
    HN: 'HN',
    HU: 'HU',
    IS: 'IS',
    IN: 'IN',
    ID: 'ID',
    IR: 'IR',
    IQ: 'IQ',
    IE: 'IE',
    IL: 'IL',
    IT: 'IT',
    JM: 'JM',
    JP: 'JP',
    JO: 'JO',
    KZ: 'KZ',
    KE: 'KE',
    KI: 'KI',
    XK: 'XK',
    KW: 'KW',
    KG: 'KG',
    LA: 'LA',
    LV: 'LV',
    LB: 'LB',
    LS: 'LS',
    LR: 'LR',
    LY: 'LY',
    LI: 'LI',
    LT: 'LT',
    LU: 'LU',
    MG: 'MG',
    MW: 'MW',
    MY: 'MY',
    MV: 'MV',
    ML: 'ML',
    MT: 'MT',
    MH: 'MH',
    MR: 'MR',
    MU: 'MU',
    MX: 'MX',
    FM: 'FM',
    MD: 'MD',
    MC: 'MC',
    MN: 'MN',
    ME: 'ME',
    MA: 'MA',
    MZ: 'MZ',
    MM: 'MM',
    NA: 'NA',
    NR: 'NR',
    NP: 'NP',
    NL: 'NL',
    NZ: 'NZ',
    NI: 'NI',
    NE: 'NE',
    NG: 'NG',
    KP: 'KP',
    MK: 'MK',
    NO: 'NO',
    OM: 'OM',
    PK: 'PK',
    PW: 'PW',
    PS: 'PS',
    PA: 'PA',
    PG: 'PG',
    PY: 'PY',
    PE: 'PE',
    PH: 'PH',
    PL: 'PL',
    PT: 'PT',
    QA: 'QA',
    RO: 'RO',
    RU: 'RU',
    RW: 'RW',
    KN: 'KN',
    LC: 'LC',
    VC: 'VC',
    WS: 'WS',
    SM: 'SM',
    ST: 'ST',
    SA: 'SA',
    SN: 'SN',
    RS: 'RS',
    SC: 'SC',
    SL: 'SL',
    SG: 'SG',
    SK: 'SK',
    SI: 'SI',
    SB: 'SB',
    SO: 'SO',
    ZA: 'ZA',
    KR: 'KR',
    SS: 'SS',
    ES: 'ES',
    LK: 'LK',
    SD: 'SD',
    SR: 'SR',
    SE: 'SE',
    CH: 'CH',
    SY: 'SY',
    TW: 'TW',
    TJ: 'TJ',
    TZ: 'TZ',
    TH: 'TH',
    TL: 'TL',
    TG: 'TG',
    TO: 'TO',
    TT: 'TT',
    TN: 'TN',
    TR: 'TR',
    TM: 'TM',
    TV: 'TV',
    UG: 'UG',
    UA: 'UA',
    AE: 'AE',
    GB: 'GB',
    US: 'US',
    UY: 'UY',
    UZ: 'UZ',
    VU: 'VU',
    VA: 'VA',
    VE: 'VE',
    VN: 'VN',
    YE: 'YE',
    ZM: 'ZM',
    ZW: 'ZW'
} as const;

/**
 * Country
 */
export type Country = typeof Country[keyof typeof Country];

/**
 * CreateCT
 *
 * for creating cursed technique
 */
export type CreateCt = {
    /**
     * Name
     *
     * The name of the cursed technique, must be between 3 and 100 characters
     */
    name: string;
    /**
     * Definition
     *
     * The definition of the cursed technique, explaining what it does without including its subsets
     */
    definition: string;
};

/**
 * CreateCTApp
 *
 * for creating a cursed technique application
 */
export type CreateCtApp = {
    /**
     * Name
     *
     * The name of the application, must be between 3 and 100 characters
     */
    name: string;
    /**
     * Application
     *
     * The application of the cursed technique, explaining how it is used or applied in practice
     */
    application: string;
};

/**
 * CreatePlayer
 *
 * For creating a Player
 */
export type CreatePlayer = {
    /**
     * Name
     *
     * The name of the player, must be between 2 and 50 characters
     */
    name: string;
    gender: Gender;
    /**
     * Age
     */
    age: number;
    /**
     * Role
     *
     * The role of the player, e.g., doctor, lawyer, student, curse user, sorcerer etc.
     */
    role?: string | null;
    /**
     * Picture
     *
     * the picture of the player
     */
    picture?: string | null;
};

/**
 * CreateUser
 *
 * For creating a user
 */
export type CreateUser = {
    /**
     * Username
     *
     * the username of the user
     */
    username: string;
    /**
     * Email
     *
     * the email address of the user
     */
    email: string;
    /**
     * the country of origin of the user
     */
    country?: Country | null;
    /**
     * Password
     *
     * the user's password
     */
    password: string;
    /**
     * Confirm Password
     *
     * the user's password
     */
    confirm_password: string;
};

/**
 * EditCT
 *
 * for editing a cursed technique
 */
export type EditCt = {
    /**
     * Name
     *
     * The name of the cursed technique, must be between 3 and 100 characters
     */
    name?: string | null;
    /**
     * Definition
     *
     * The definition of the cursed technique, explaining what it does without including its subsets
     */
    definition?: string | null;
};

/**
 * EditCTApp
 *
 * for editing a cursed technique application
 */
export type EditCtApp = {
    /**
     * Number
     */
    number: number;
    /**
     * Name
     *
     * The name of the application, must be between 3 and 100 characters
     */
    name?: string | null;
    /**
     * Application
     *
     * The application of the cursed technique, explaining how it is used or applied in practice
     */
    application?: string | null;
};

/**
 * EditPlayer
 *
 * For editing a Player
 */
export type EditPlayer = {
    /**
     * Name
     *
     * The name of the player, must be between 2 and 50 characters
     */
    name?: string | null;
    gender?: Gender | null;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Role
     *
     * The role of the player, e.g., doctor, lawyer, student, curse user, sorcerer etc.
     */
    role?: string | null;
    /**
     * Picture
     *
     * the picture of the player
     */
    picture?: string | null;
};

/**
 * EditUser
 *
 * For editing a User
 */
export type EditUser = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
    country?: Country | null;
};

/**
 * Gender
 *
 * the player gender options
 */
export const Gender = {
    MALE: 'male',
    FEMALE: 'female',
    NON_BINARY: 'non-binary'
} as const;

/**
 * Gender
 *
 * the player gender options
 */
export type Gender = typeof Gender[keyof typeof Gender];

/**
 * Grade
 *
 * the enum class for player grades
 */
export const Grade = {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4
} as const;

/**
 * Grade
 *
 * the enum class for player grades
 */
export type Grade = typeof Grade[keyof typeof Grade];

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MatchInfo
 *
 * match info for client side
 */
export type MatchInfo = {
    /**
     * Begin
     *
     * The start time of the match
     */
    begin: string;
    /**
     * End
     *
     * The end time of the match
     */
    end: string;
    /**
     * Part
     */
    part: number;
    /**
     * Draw
     *
     * whether the match was a draw
     */
    draw?: boolean;
    /**
     * Id
     */
    id: number;
    winner: BasePlayerInfo | null;
    /**
     * Players
     */
    players: Array<BasePlayerInfo>;
    colony: BaseColonyInfo;
    /**
     * Votes
     */
    votes: Array<BaseVoteInfo>;
    /**
     * Barrier Records
     */
    barrier_records: Array<BarrierRecordInfo>;
};

/**
 * ModelName
 *
 * class for the enum of database table names.
 */
export const ModelName = {
    COLONY: 'colony',
    USER: 'user',
    BARRIERTECH: 'barriertech',
    BARRIERRECORD: 'barrierrecord',
    VOTE: 'vote',
    PLAYER: 'player',
    CURSEDTECHNIQUE: 'cursedtechnique',
    CTAPP: 'ctapp',
    MATCH: 'match',
    ADMIN: 'admin',
    PERMISSION: 'permission'
} as const;

/**
 * ModelName
 *
 * class for the enum of database table names.
 */
export type ModelName = typeof ModelName[keyof typeof ModelName];

/**
 * PermissionInfo
 */
export type PermissionInfo = {
    /**
     * The model the permission applies to
     */
    model: ModelName;
    /**
     * Id
     */
    id: number;
    /**
     * Name
     *
     * Permission name
     */
    name: string;
    level: PermissionLevel;
};

/**
 * PermissionLevel
 */
export const PermissionLevel = {
    1: 1,
    2: 2,
    3: 3,
    4: 4
} as const;

/**
 * PermissionLevel
 */
export type PermissionLevel = typeof PermissionLevel[keyof typeof PermissionLevel];

/**
 * PermissionRequest
 *
 * Model for collecting A Permission request
 */
export type PermissionRequest = {
    /**
     * The model the permission applies to
     */
    model: ModelName;
    /**
     * Levels
     */
    levels: Array<PermissionLevel>;
};

/**
 * PlayerInfo
 *
 * Player info with cursed technique, user, and colony info
 */
export type PlayerInfo = {
    /**
     * Name
     *
     * The name of the player, must be between 2 and 50 characters
     */
    name: string;
    gender: Gender;
    /**
     * Age
     */
    age: number;
    /**
     * Role
     *
     * The role of the player, e.g., doctor, lawyer, student, curse user, sorcerer etc.
     */
    role?: string | null;
    /**
     * Picture
     *
     * the picture of the player
     */
    picture?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created
     */
    created: string;
    grade: Grade;
    /**
     * Points
     */
    points: number;
    /**
     * Alive
     */
    alive: boolean;
    cursed_technique: BaseCtInfo;
    barrier_technique: BarrierTechInfo | null;
    colony: BaseColonyInfo | null;
    user: BaseUserInfo | null;
    /**
     * Matches
     */
    matches: Array<BaseMatchInfo>;
    /**
     * Votes
     */
    votes: Array<BaseVoteInfo>;
};

/**
 * Token
 *
 * model for encoded access token, resfresh token,
 * and acces token expires time
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type: string;
    /**
     * Expires In
     */
    expires_in: number;
    /**
     * Refresh Expires In
     */
    refresh_expires_in: number;
};

/**
 * TokenData
 *
 * response model for decoded token
 */
export type TokenData = {
    /**
     * Sub
     */
    sub: string;
    /**
     * Refresh Token Key
     */
    refresh_token_key?: string | null;
    /**
     * Exp
     */
    exp: string;
    /**
     * Iat
     */
    iat: string;
    /**
     * Scopes
     */
    scopes?: Array<string>;
};

/**
 * UserInfo
 *
 * The user info
 */
export type UserInfo = {
    /**
     * Username
     *
     * the username of the user
     */
    username: string;
    /**
     * Email
     *
     * the email address of the user
     */
    email: string;
    /**
     * the country of origin of the user
     */
    country?: Country | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created
     *
     * the date the account was created
     */
    created: string;
    player?: BasePlayerInfo | null;
    admin?: BaseAdminInfo | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type CurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type CurrentUserResponses = {
    /**
     * A User
     */
    200: UserInfo;
};

export type CurrentUserResponse = CurrentUserResponses[keyof CurrentUserResponses];

export type AUserData = {
    body?: never;
    path: {
        /**
         * User
         *
         * The user's Id, Username, or Email
         */
        user: number | string;
    };
    query?: never;
    url: '/users/{user}';
};

export type AUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AUserError = AUserErrors[keyof AUserErrors];

export type AUserResponses = {
    /**
     * A User
     */
    200: UserInfo;
};

export type AUserResponse = AUserResponses[keyof AUserResponses];

export type EditUserData = {
    body: EditUser;
    path: {
        /**
         * User
         *
         * The user's Id, Username, or Email
         */
        user: number | string;
    };
    query?: never;
    url: '/users/edit/{user}';
};

export type EditUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditUserError = EditUserErrors[keyof EditUserErrors];

export type EditUserResponses = {
    /**
     * Edited User
     */
    200: UserInfo;
};

export type EditUserResponse = EditUserResponses[keyof EditUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User
         *
         * The user's Id, Username, or Email
         */
        user: number | string;
    };
    query?: never;
    url: '/users/delete/{user}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Deleted User
     */
    200: UserInfo;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type CreatePlayerData = {
    body: BodyCreatePlayer;
    path: {
        /**
         * User
         *
         * The user's Id, Username, or Email
         */
        user: number | string;
    };
    query?: never;
    url: '/player/create/{user}';
};

export type CreatePlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePlayerError = CreatePlayerErrors[keyof CreatePlayerErrors];

export type CreatePlayerResponses = {
    /**
     * New Player
     */
    201: PlayerInfo;
};

export type CreatePlayerResponse = CreatePlayerResponses[keyof CreatePlayerResponses];

export type MyPlayerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/player/me';
};

export type MyPlayerResponses = {
    /**
     * A Player
     */
    200: PlayerInfo;
};

export type MyPlayerResponse = MyPlayerResponses[keyof MyPlayerResponses];

export type GetPlayersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Slim
         *
         * If true, minimal player info will be returned
         */
        slim?: boolean;
        /**
         * Gender
         */
        gender?: Gender | null;
        /**
         * Age
         */
        age?: number | null;
        /**
         * Role
         */
        role?: string | null;
        /**
         * Alive
         */
        alive?: boolean;
    };
    url: '/player/all';
};

export type GetPlayersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlayersError = GetPlayersErrors[keyof GetPlayersErrors];

export type GetPlayersResponses = {
    /**
     * Response Get Players
     *
     * A list of players
     */
    200: Array<PlayerInfo> | Array<BasePlayerInfo>;
};

export type GetPlayersResponse = GetPlayersResponses[keyof GetPlayersResponses];

export type APlayerData = {
    body?: never;
    path: {
        /**
         * Player Id
         *
         * the player id
         */
        player_id: number;
    };
    query?: {
        /**
         * Alive
         *
         * whether the player has to be alive
         */
        alive?: boolean;
    };
    url: '/player/{player_id}';
};

export type APlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type APlayerError = APlayerErrors[keyof APlayerErrors];

export type APlayerResponses = {
    /**
     * A Player
     */
    200: PlayerInfo;
};

export type APlayerResponse = APlayerResponses[keyof APlayerResponses];

export type EditPlayerData = {
    /**
     * Body
     */
    body?: BodyEditPlayer;
    path: {
        /**
         * Player Id
         *
         * the player id
         */
        player_id: number;
    };
    query?: never;
    url: '/player/edit/{player_id}';
};

export type EditPlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditPlayerError = EditPlayerErrors[keyof EditPlayerErrors];

export type EditPlayerResponses = {
    /**
     * Edited Player
     */
    200: PlayerInfo;
};

export type EditPlayerResponse = EditPlayerResponses[keyof EditPlayerResponses];

export type DeletePlayerData = {
    body?: never;
    path: {
        /**
         * Player Id
         *
         * the player id
         */
        player_id: number;
    };
    query?: never;
    url: '/player/delete/{player_id}';
};

export type DeletePlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePlayerError = DeletePlayerErrors[keyof DeletePlayerErrors];

export type DeletePlayerResponses = {
    /**
     * A deleted player
     */
    200: PlayerInfo;
};

export type DeletePlayerResponse = DeletePlayerResponses[keyof DeletePlayerResponses];

export type UpgradePlayerData = {
    body?: never;
    path: {
        /**
         * Player Id
         *
         * the player id
         */
        player_id: number;
    };
    query: {
        /**
         * Grade Up
         *
         * specified upgrade
         */
        grade_up: Grade;
    };
    url: '/player/upgrade/{player_id}';
};

export type UpgradePlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpgradePlayerError = UpgradePlayerErrors[keyof UpgradePlayerErrors];

export type UpgradePlayerResponses = {
    /**
     * Successful Response
     */
    200: PlayerInfo;
};

export type UpgradePlayerResponse = UpgradePlayerResponses[keyof UpgradePlayerResponses];

export type VoteData = {
    /**
     * Votes
     */
    body: Array<CastVote>;
    path: {
        /**
         * Match Id
         */
        match_id: number;
    };
    query?: never;
    url: '/match/vote/{match_id}';
};

export type VoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VoteError = VoteErrors[keyof VoteErrors];

export type VoteResponses = {
    /**
     * Successful Response
     */
    200: ClientVoteInfo;
};

export type VoteResponse = VoteResponses[keyof VoteResponses];

export type CreateMatchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Part
         */
        part: number;
    };
    url: '/match/create';
};

export type CreateMatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMatchError = CreateMatchErrors[keyof CreateMatchErrors];

export type CreateMatchResponses = {
    /**
     * Successful Response
     */
    201: MatchInfo;
};

export type CreateMatchResponse = CreateMatchResponses[keyof CreateMatchResponses];

export type GetMatchesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/match/all';
};

export type GetMatchesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMatchesError = GetMatchesErrors[keyof GetMatchesErrors];

export type GetMatchesResponses = {
    /**
     * Response Get Matches
     *
     * Successful Response
     */
    200: Array<MatchInfo>;
};

export type GetMatchesResponse = GetMatchesResponses[keyof GetMatchesResponses];

export type GetLastestMatchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Ongoing
         *
         * should be an ongoing match
         */
        ongoing?: boolean;
    };
    url: '/match/latest';
};

export type GetLastestMatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLastestMatchError = GetLastestMatchErrors[keyof GetLastestMatchErrors];

export type GetLastestMatchResponses = {
    /**
     * Successful Response
     */
    200: MatchInfo;
};

export type GetLastestMatchResponse = GetLastestMatchResponses[keyof GetLastestMatchResponses];

export type DeleteMatchData = {
    body?: never;
    path: {
        /**
         * Match Id
         */
        match_id: number;
    };
    query?: never;
    url: '/match/delete/{match_id}';
};

export type DeleteMatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMatchError = DeleteMatchErrors[keyof DeleteMatchErrors];

export type DeleteMatchResponses = {
    /**
     * Successful Response
     */
    200: MatchInfo;
};

export type DeleteMatchResponse = DeleteMatchResponses[keyof DeleteMatchResponses];

export type AssignMatchWinnerData = {
    body?: never;
    path: {
        /**
         * Match Id
         */
        match_id: number;
    };
    query?: never;
    url: '/match/winner/{match_id}';
};

export type AssignMatchWinnerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignMatchWinnerError = AssignMatchWinnerErrors[keyof AssignMatchWinnerErrors];

export type AssignMatchWinnerResponses = {
    /**
     * Successful Response
     */
    200: MatchInfo;
};

export type AssignMatchWinnerResponse = AssignMatchWinnerResponses[keyof AssignMatchWinnerResponses];

export type DomainExpansionData = {
    body?: never;
    path: {
        /**
         * Player Id
         */
        player_id: number;
        /**
         * Match Id
         */
        match_id: number;
    };
    query?: never;
    url: '/barrier/activate/domain/{player_id}/{match_id}';
};

export type DomainExpansionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DomainExpansionError = DomainExpansionErrors[keyof DomainExpansionErrors];

export type DomainExpansionResponses = {
    /**
     * Successful Response
     */
    200: BarrierTechInfo;
};

export type DomainExpansionResponse = DomainExpansionResponses[keyof DomainExpansionResponses];

export type SimpleDomainData = {
    body?: never;
    path: {
        /**
         * Player Id
         */
        player_id: number;
        /**
         * Match Id
         */
        match_id: number;
    };
    query?: never;
    url: '/barrier/activate/simple/{player_id}/{match_id}';
};

export type SimpleDomainErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SimpleDomainError = SimpleDomainErrors[keyof SimpleDomainErrors];

export type SimpleDomainResponses = {
    /**
     * Successful Response
     */
    200: BarrierTechInfo;
};

export type SimpleDomainResponse = SimpleDomainResponses[keyof SimpleDomainResponses];

export type BindindVowData = {
    body?: never;
    path: {
        /**
         * Player Id
         */
        player_id: number;
        /**
         * Match Id
         */
        match_id: number;
    };
    query?: never;
    url: '/barrier/activate/binding/{player_id}/{match_id}';
};

export type BindindVowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BindindVowError = BindindVowErrors[keyof BindindVowErrors];

export type BindindVowResponses = {
    /**
     * Successful Response
     */
    200: BarrierTechInfo;
};

export type BindindVowResponse = BindindVowResponses[keyof BindindVowResponses];

export type ReverseCursedTechniqueData = {
    body?: never;
    path: {
        /**
         * Player Id
         */
        player_id: number;
        /**
         * Match Id
         */
        match_id: number;
    };
    query?: never;
    url: '/barrier/activate/rct/{player_id}/{match_id}';
};

export type ReverseCursedTechniqueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReverseCursedTechniqueError = ReverseCursedTechniqueErrors[keyof ReverseCursedTechniqueErrors];

export type ReverseCursedTechniqueResponses = {
    /**
     * Successful Response
     */
    200: BarrierTechInfo;
};

export type ReverseCursedTechniqueResponse = ReverseCursedTechniqueResponses[keyof ReverseCursedTechniqueResponses];

export type DeactivateDomainExpansionData = {
    body?: never;
    path: {
        /**
         * Player Id
         */
        player_id: number;
    };
    query?: never;
    url: '/barrier/deactivate/barrier/{player_id}';
};

export type DeactivateDomainExpansionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeactivateDomainExpansionError = DeactivateDomainExpansionErrors[keyof DeactivateDomainExpansionErrors];

export type DeactivateDomainExpansionResponses = {
    /**
     * Successful Response
     */
    200: BarrierTechInfo;
};

export type DeactivateDomainExpansionResponse = DeactivateDomainExpansionResponses[keyof DeactivateDomainExpansionResponses];

export type GetColoniesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/colony/all';
};

export type GetColoniesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetColoniesError = GetColoniesErrors[keyof GetColoniesErrors];

export type GetColoniesResponses = {
    /**
     * Response Get Colonies
     *
     * Successful Response
     */
    200: Array<ColonyInfo>;
};

export type GetColoniesResponse = GetColoniesResponses[keyof GetColoniesResponses];

export type DemoSuperuserData = {
    body?: never;
    path: {
        /**
         * User
         *
         * The user's Id, Username, or Email
         */
        user: number | string;
    };
    query: {
        /**
         * Code
         */
        code: string;
    };
    url: '/admin/superuser/{user}';
};

export type DemoSuperuserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DemoSuperuserError = DemoSuperuserErrors[keyof DemoSuperuserErrors];

export type DemoSuperuserResponses = {
    /**
     * Successful Response
     */
    200: AdminInfo;
};

export type DemoSuperuserResponse = DemoSuperuserResponses[keyof DemoSuperuserResponses];

export type AdminEditUserData = {
    body: EditUser;
    path: {
        /**
         * User
         *
         * The user's Id, Username, or Email
         */
        user: number | string;
    };
    query?: never;
    url: '/admin/edit-user/{user}';
};

export type AdminEditUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminEditUserError = AdminEditUserErrors[keyof AdminEditUserErrors];

export type AdminEditUserResponses = {
    /**
     * Edited User
     */
    200: UserInfo;
};

export type AdminEditUserResponse = AdminEditUserResponses[keyof AdminEditUserResponses];

export type AdminDeleteUserData = {
    body?: never;
    path: {
        /**
         * User
         *
         * The user's Id, Username, or Email
         */
        user: number | string;
    };
    query?: never;
    url: '/admin/delete-user/{user}';
};

export type AdminDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteUserError = AdminDeleteUserErrors[keyof AdminDeleteUserErrors];

export type AdminDeleteUserResponses = {
    /**
     * Deleted User
     */
    200: UserInfo;
};

export type AdminDeleteUserResponse = AdminDeleteUserResponses[keyof AdminDeleteUserResponses];

export type AdminEditPlayerData = {
    /**
     * Body
     */
    body?: BodyAdminEditPlayer;
    path: {
        /**
         * Player Id
         *
         * the player id
         */
        player_id: number;
    };
    query?: never;
    url: '/admin/edit-player/{player_id}';
};

export type AdminEditPlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminEditPlayerError = AdminEditPlayerErrors[keyof AdminEditPlayerErrors];

export type AdminEditPlayerResponses = {
    /**
     * Edited Player
     */
    200: PlayerInfo;
};

export type AdminEditPlayerResponse = AdminEditPlayerResponses[keyof AdminEditPlayerResponses];

export type AdminDeletePlayerData = {
    body?: never;
    path: {
        /**
         * Player Id
         *
         * the player id
         */
        player_id: number;
    };
    query?: never;
    url: '/admin/delete-player/{player_id}';
};

export type AdminDeletePlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeletePlayerError = AdminDeletePlayerErrors[keyof AdminDeletePlayerErrors];

export type AdminDeletePlayerResponses = {
    /**
     * A deleted player
     */
    200: PlayerInfo;
};

export type AdminDeletePlayerResponse = AdminDeletePlayerResponses[keyof AdminDeletePlayerResponses];

export type CreateAdminData = {
    /**
     * Permissions
     */
    body: Array<PermissionRequest>;
    path: {
        /**
         * User
         *
         * The user's Id, Username, or Email
         */
        user: number | string;
    };
    query?: never;
    url: '/admin/create/{user}';
};

export type CreateAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAdminError = CreateAdminErrors[keyof CreateAdminErrors];

export type CreateAdminResponses = {
    /**
     * Successful Response
     */
    200: AdminInfo;
};

export type CreateAdminResponse = CreateAdminResponses[keyof CreateAdminResponses];

export type NewPermissionData = {
    /**
     * Permissions
     */
    body: Array<PermissionRequest>;
    path?: never;
    query?: never;
    url: '/admin/new-permission';
};

export type NewPermissionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewPermissionError = NewPermissionErrors[keyof NewPermissionErrors];

export type NewPermissionResponses = {
    /**
     * Response New Permission
     *
     * Successful Response
     */
    200: Array<PermissionInfo>;
};

export type NewPermissionResponse = NewPermissionResponses[keyof NewPermissionResponses];

export type GrantPermissionData = {
    /**
     * Permissions
     */
    body: Array<PermissionRequest>;
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/admin/grant-permission/{admin_id}';
};

export type GrantPermissionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GrantPermissionError = GrantPermissionErrors[keyof GrantPermissionErrors];

export type GrantPermissionResponses = {
    /**
     * Successful Response
     */
    200: AdminInfo;
};

export type GrantPermissionResponse = GrantPermissionResponses[keyof GrantPermissionResponses];

export type RemovePermissionData = {
    /**
     * Permissions
     */
    body: Array<PermissionRequest>;
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/admin/remove-permission/{admin_id}';
};

export type RemovePermissionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemovePermissionError = RemovePermissionErrors[keyof RemovePermissionErrors];

export type RemovePermissionResponses = {
    /**
     * Successful Response
     */
    200: AdminInfo;
};

export type RemovePermissionResponse = RemovePermissionResponses[keyof RemovePermissionResponses];

export type CurrentAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/me';
};

export type CurrentAdminResponses = {
    /**
     * An Admin
     */
    200: AdminInfo;
};

export type CurrentAdminResponse = CurrentAdminResponses[keyof CurrentAdminResponses];

export type CreateTokenData = {
    body: BodyCreateToken;
    path?: never;
    query?: never;
    url: '/login';
};

export type CreateTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTokenError = CreateTokenErrors[keyof CreateTokenErrors];

export type CreateTokenResponses = {
    /**
     * A Token
     */
    200: Token;
};

export type CreateTokenResponse = CreateTokenResponses[keyof CreateTokenResponses];

export type RefreshTokenData = {
    body: BodyRefreshToken;
    path?: never;
    query?: never;
    url: '/refresh-token';
};

export type RefreshTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * An Updated Token
     */
    200: Token;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type VerifyTokenData = {
    body: BodyVerifyToken;
    path?: never;
    query?: never;
    url: '/verify-token';
};

export type VerifyTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyTokenError = VerifyTokenErrors[keyof VerifyTokenErrors];

export type VerifyTokenResponses = {
    /**
     * A Verified Token
     */
    200: TokenData;
};

export type VerifyTokenResponse = VerifyTokenResponses[keyof VerifyTokenResponses];

export type CreateUserData = {
    /**
     * User
     *
     * The details for creating a User
     */
    body: CreateUser;
    path?: never;
    query?: never;
    url: '/signup';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * New User
     */
    201: UserInfo;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type HomePageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type HomePageResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type HomePageResponse = HomePageResponses[keyof HomePageResponses];
