name: CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DATABASE_URL }}

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.11"
          enable-cache: true
          # invalidate it when the lockfile changes
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Generate ModelName enum
        run: python app/scripts/gen_table_enum.py

      - name: Run migrations
        run: uv run alembic upgrade head

      - name: Run tests
        run: uv run pytest

      - name: Push Backend API to Production
        run: git subtree push --prefix backend https://github.com/CrusaderGoT/The-Culling-Games-Backend.git principal
