name: ROOT CI

on:
  push:
    branches: [principal]
    paths:
      - "backend/**"
  pull_request:
    branches: [principal]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for subtree splitting
          persist-credentials: false # we’ll supply our own creds

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add backend remote with PAT
        run: |
          git remote add backend \
            https://x-access-token:${{ secrets.SUBTREE_TOKEN }}@github.com/CrusaderGoT/The-Culling-Games-Backend.git

      - name: Push backend subtree to remote
        run: |
          git subtree push git subtree push --prefix backend backend principal
