name: ROOT CI

on:
  push:
    branches: [principal]
    paths:
      - "backend/**"
  pull_request:
    branches: [principal]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push backend subtree to remote
        # avoid rerunning this job on subtree push:
        if: github.event_name != 'workflow_dispatch'
        run: |
          git subtree push \
            --prefix backend \
            https://github.com/CrusaderGoT/The-Culling-Games-Backend.git \
            principal
